language: java
jdk:
  - oraclejdk8

env:
  - GRAAL_VERSION=1.0.0-rc6
  - GRAAL_HOME=~/graalvm

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl

install:
  - mkdir $GRAAL_HOME && \
    curl -fsSL "https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-linux-amd64.tar.gz" | tar -zxC /graalvm --strip-components 1 && \

script: ./gradlew build

deploy:
  provider: releases
  api_key: $githubToken
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true