language: java
jdk:
  - oraclejdk8
script: ./gradlew build

deploy:
  provider: releases
  api_key: $githubToken
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true