language: java
jdk:
  - oraclejdk8

env:
  global:
    - GRAAL_VERSION=1.0.0-rc6
    - GRAAL_HOME=/home/travis/graalvm

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl
  - mkdir $GRAAL_HOME
  - curl -fsSL "https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-linux-amd64.tar.gz" | tar -zxC $GRAAL_HOME --strip-components=1

script: ./gradlew build

deploy:
  provider: releases
  api_key: $githubToken
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true