package br.com.softbox.thrust.util;

import java.util.Base64;

import javax.script.ScriptContext;
import javax.script.ScriptEngine;
import javax.script.ScriptException;

public class ThrustUtils {
	private static final String POLYFILLS_ENCODED = "dmFyIGdsb2JhbCA9IHRoaXM7DQp2YXIgc2VsZiA9IHRoaXM7DQp2YXIgd2luZG93ID0gdGhpczsNCnZhciBwcm9jZXNzID0ge2Vudjoge319Ow0KdmFyIGNvbnNvbGUgPSB7fTsNCmNvbnNvbGUuZGVidWcgPSBwcmludDsNCmNvbnNvbGUud2FybiA9IHByaW50Ow0KY29uc29sZS5sb2cgPSBwcmludDsNCmNvbnNvbGUuZXJyb3IgPSBwcmludDsNCmNvbnNvbGUudHJhY2UgPSBwcmludDsNCg0KDQp2YXIgSlN0cmluZyA9IGphdmEubGFuZy5TdHJpbmcNCnZhciBTdGFuZGFyZENoYXJzZXRzID0gSmF2YS50eXBlKCdqYXZhLm5pby5jaGFyc2V0LlN0YW5kYXJkQ2hhcnNldHMnKQ0KdmFyIGRlY29kZXIgPSBqYXZhLnV0aWwuQmFzZTY0LmdldERlY29kZXIoKQ0KdmFyIGVuY29kZXIgPSBqYXZhLnV0aWwuQmFzZTY0LmdldEVuY29kZXIoKQ0KDQpmdW5jdGlvbiBidG9hKGRlY29kZWRTdHJpbmcpIHsNCiAgICByZXR1cm4gIG5ldyBTdHJpbmcobmV3IEpTdHJpbmcoIGVuY29kZXIuZW5jb2RlKG5ldyBKU3RyaW5nKGRlY29kZWRTdHJpbmcpLmdldEJ5dGVzKFN0YW5kYXJkQ2hhcnNldHMuVVRGXzgpKSApICkNCn0NCg0KZnVuY3Rpb24gYXRvYihlbmNvZGVkU3RyaW5nKSB7DQogICAgcmV0dXJuIG5ldyBTdHJpbmcobmV3IEpTdHJpbmcoZGVjb2Rlci5kZWNvZGUobmV3IEpTdHJpbmcoZW5jb2RlZFN0cmluZykuZ2V0Qnl0ZXMoU3RhbmRhcmRDaGFyc2V0cy5VVEZfOCkpKSkNCn0NCg0KDQppZiAoIU9iamVjdC5hc3NpZ24pIHsNCiAgICBPYmplY3QuZGVmaW5lUHJvcGVydHkoT2JqZWN0LCAnYXNzaWduJywgew0KICAgICAgICBlbnVtZXJhYmxlOiBmYWxzZSwNCiAgICAgICAgY29uZmlndXJhYmxlOiB0cnVlLA0KICAgICAgICB3cml0YWJsZTogdHJ1ZSwNCiAgICAgICAgdmFsdWU6IGZ1bmN0aW9uICh0YXJnZXQpIHsNCiAgICAgICAgICAgICd1c2Ugc3RyaWN0JzsNCiAgICAgICAgICAgIGlmICh0YXJnZXQgPT09IHVuZGVmaW5lZCB8fCB0YXJnZXQgPT09IG51bGwpIHsNCiAgICAgICAgICAgICAgICB0aHJvdyBuZXcgVHlwZUVycm9yKCdDYW5ub3QgY29udmVydCBmaXJzdCBhcmd1bWVudCB0byBvYmplY3QnKTsNCiAgICAgICAgICAgIH0NCg0KICAgICAgICAgICAgdmFyIHRvID0gT2JqZWN0KHRhcmdldCk7DQogICAgICAgICAgICBmb3IgKHZhciBpID0gMTsgaSA8IGFyZ3VtZW50cy5sZW5ndGg7IGkrKykgew0KICAgICAgICAgICAgICAgIHZhciBuZXh0U291cmNlID0gYXJndW1lbnRzW2ldOw0KICAgICAgICAgICAgICAgIGlmIChuZXh0U291cmNlID09PSB1bmRlZmluZWQgfHwgbmV4dFNvdXJjZSA9PT0gbnVsbCkgew0KICAgICAgICAgICAgICAgICAgICBjb250aW51ZTsNCiAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgbmV4dFNvdXJjZSA9IE9iamVjdChuZXh0U291cmNlKTsNCg0KICAgICAgICAgICAgICAgIHZhciBrZXlzQXJyYXkgPSBPYmplY3Qua2V5cyhPYmplY3QobmV4dFNvdXJjZSkpOw0KICAgICAgICAgICAgICAgIGZvciAodmFyIG5leHRJbmRleCA9IDAsIGxlbiA9IGtleXNBcnJheS5sZW5ndGg7IG5leHRJbmRleCA8IGxlbjsgbmV4dEluZGV4KyspIHsNCiAgICAgICAgICAgICAgICAgICAgdmFyIG5leHRLZXkgPSBrZXlzQXJyYXlbbmV4dEluZGV4XTsNCiAgICAgICAgICAgICAgICAgICAgdmFyIGRlc2MgPSBPYmplY3QuZ2V0T3duUHJvcGVydHlEZXNjcmlwdG9yKG5leHRTb3VyY2UsIG5leHRLZXkpOw0KICAgICAgICAgICAgICAgICAgICBpZiAoZGVzYyAhPT0gdW5kZWZpbmVkICYmIGRlc2MuZW51bWVyYWJsZSkgew0KICAgICAgICAgICAgICAgICAgICAgICAgdG9bbmV4dEtleV0gPSBuZXh0U291cmNlW25leHRLZXldOw0KICAgICAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgfQ0KICAgICAgICAgICAgcmV0dXJuIHRvOw0KICAgICAgICB9DQogICAgfSk7DQp9DQoNCg0KaWYgKCFPYmplY3QudmFsdWVzKSB7DQogICAgT2JqZWN0LnZhbHVlcyA9IGZ1bmN0aW9uIHZhbHVlcyh0YXJnZXQpIHsNCiAgICAgICAgcmV0dXJuIE9iamVjdC5nZXRPd25Qcm9wZXJ0eU5hbWVzKHRhcmdldCkubWFwKGZ1bmN0aW9uIChrKSB7DQogICAgICAgICAgICByZXR1cm4gdGFyZ2V0W2tdDQogICAgICAgIH0pDQogICAgfQ0KfQ0KDQoNCmlmICghQXJyYXkucHJvdG90eXBlLmZpbmQpIHsNCiAgICBPYmplY3QuZGVmaW5lUHJvcGVydHkoQXJyYXkucHJvdG90eXBlLCAnZmluZCcsIHsNCiAgICAgICAgdmFsdWU6IGZ1bmN0aW9uIChwcmVkaWNhdGUpIHsNCiAgICAgICAgICAgIGlmICh0aGlzID09IG51bGwpIHsNCiAgICAgICAgICAgICAgICB0aHJvdyBuZXcgVHlwZUVycm9yKCcidGhpcyIgaXMgbnVsbCBvciBub3QgZGVmaW5lZCcpOw0KICAgICAgICAgICAgfQ0KDQogICAgICAgICAgICB2YXIgbyA9IE9iamVjdCh0aGlzKTsNCiAgICAgICAgICAgIHZhciBsZW4gPSBvLmxlbmd0aCA+Pj4gMDsNCg0KICAgICAgICAgICAgaWYgKHR5cGVvZiBwcmVkaWNhdGUgIT09ICdmdW5jdGlvbicpIHsNCiAgICAgICAgICAgICAgICB0aHJvdyBuZXcgVHlwZUVycm9yKCdwcmVkaWNhdGUgbXVzdCBiZSBhIGZ1bmN0aW9uJyk7DQogICAgICAgICAgICB9DQoNCiAgICAgICAgICAgIHZhciB0aGlzQXJnID0gYXJndW1lbnRzWzFdOw0KICAgICAgICAgICAgdmFyIGsgPSAwOw0KDQogICAgICAgICAgICB3aGlsZSAoayA8IGxlbikgew0KICAgICAgICAgICAgICAgIHZhciBrVmFsdWUgPSBvW2tdOw0KICAgICAgICAgICAgICAgIGlmIChwcmVkaWNhdGUuY2FsbCh0aGlzQXJnLCBrVmFsdWUsIGssIG8pKSB7DQogICAgICAgICAgICAgICAgICAgIHJldHVybiBrVmFsdWU7DQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgIGsrKzsNCiAgICAgICAgICAgIH0NCg0KICAgICAgICAgICAgcmV0dXJuIHVuZGVmaW5lZDsNCiAgICAgICAgfQ0KICAgIH0pOw0KfQ0K";
	private static final String REQUIRE_WRAPPER_ENCODED = "ZnVuY3Rpb24gcmVxdWlyZShmaWxlTmFtZSkgew0KICAgIGNvbnN0IFRocnVzdENvcmUgPSBKYXZhLnR5cGUoImJyLmNvbS5zb2Z0Ym94LnRocnVzdC5jb3JlLlRocnVzdENvcmUiKQ0KICAgIGNvbnN0IG1hcCA9IFRocnVzdENvcmUucmVxdWlyZShmaWxlTmFtZSkNCiAgICBjb25zdCBhdHRycyA9IHt9DQogICAgZm9yICh2YXIga2V5IGluIG1hcCkgew0KICAgICAgICBhdHRyc1trZXldID0gbWFwW2tleV0NCiAgICB9DQogICAgcmV0dXJuIGF0dHJzDQp9";
	
	private static String polyfills = null;
	private static String requireWrapper = null;
	
	static {
		polyfills = new String(Base64.getDecoder().decode(ThrustUtils.POLYFILLS_ENCODED));
		requireWrapper = new String(Base64.getDecoder().decode(ThrustUtils.REQUIRE_WRAPPER_ENCODED));
	}
	
	public static void loadPolyfills(ScriptEngine engine, ScriptContext context) throws ScriptException {
		loadOnContext(engine, context, polyfills);
	}

	public static void loadRequireWrapper(ScriptEngine engine, ScriptContext context) throws ScriptException {
		loadOnContext(engine, context, requireWrapper);
	}

	public static void loadConfig(ScriptEngine engine, ScriptContext context) throws ScriptException {
		loadOnContext(engine, context, "var config = {prop1:'value1'}\n");
	}

	private static void loadOnContext(ScriptEngine engine, ScriptContext scriptContext, String scriptContent)
			throws ScriptException {
		if (engine == null || scriptContext == null) {
			throw new IllegalStateException("[ERROR] \"engine\" and \"scriptContext\" params must be not null.");
		}
		
		if (scriptContent == null || scriptContent.length() < 1) {
			throw new IllegalStateException("[ERROR] \"scriptContent\" param must be not null or empty.");
		}

		engine.eval(scriptContent, scriptContext);
	}
}
